"""Observed positional headers; whitespace is cosmetic, positions are not."""
HEADERS = {
    'B2B FOLLOW UP': ['Engage Date', 'Follow Up Call', 'Phone No.', 'Ad /B2B Cold',
        'Business Name', 'Business Type', 'Status', 'Who did Site Visit',
        'Price @ Site Visit', 'F/U Call', 'Feedback from call',
        'Decision Maker Present During Site visit', 'Remark', 'Closing Date',
        'Appointment Date', 'Quotation Sent', 'F/U1 (WA)', 'F/U2 (WA)', 'F/U3 (WA)',
        'F/U4 (WA)', 'Lead to Appointment', 'Appointment to Close', '', '', ''],
    'SALES': ['11', 'PIC', 'Time Stamp', 'Closed Date', 'First Contact Date', '#VALUE!',
        'CUSTOMER ID', 'Ad', 'Customer Name', 'No Telefon', 'Alamat', 'EMEL',
        'PREMISE (RESIDENTIAL / COMMERCIAL)', 'Total Session', 'Done Session',
        'Balance Session', 'First Session Date', 'Second Session Date',
        'Third Session Date', 'PREVIOUS SESSION (Subscription)',
        'Next Session Date (Subscription)', 'TRBS (YES / NO)', 'TRBS COLLECTION DATE',
        'CLEAR / DEPOSIT', 'TYPE OF PEST', 'TYPE OF PACKAGE', 'CONTRACT TYPE',
        'Total (RM)', 'DEPOSIT PAID (RM)', 'INVOICE ID', 'BALANCE PAID (RM)',
        'INVOICE ID', '#VALUE!', 'GPC UPSELL A (5 DAYS)', 'GPC UPSELL B (6 DAYS)',
        'GPC UPSELL C (7 DAYS)', 'GPC UPSELL D (1 DAY AFTER 3RD SERVICE)',
        'GPC UPSELL E (31 DAY AFTER 3RD SERVICE)', 'GPC UPSELL F (36 DAY AFTER 3RD SERVICE)',
        'Fill in remark', 'REMARK', 'TECHNICIAN UPSELL', 'Review'],
    'PAYMENTS': ['Date', 'Customer ID', 'Amount (RM)', 'Recipient Reference',
        'Customer Name', 'Payment Method', 'Complete / Pending', 'Remarks', 'EXTRA', '', '', ''],
    'PAYMENT LINK': ['Date', 'Phone Number', 'INFO REQUESTED', 'INVOICE SHARED',
        'WON / PENDING', 'REMARKS', '', '', ''],
    'WARRANTY CLAIM': ['Date', 'Customer ID', 'Purchase Date', 'Warranty End Date',
        'Complimentary Service Date', 'Warranty Claim (Service) Date', 'Refund Date',
        '1st Service TECHNICIAN', '2nd Service TECHNICIAN', '3rd Service TECHNICIAN',
        '4th Service TECHNICIAN', '5th Service TECHNICIAN', '6th Service TECHNICIAN',
        '7th Service TECHNICIAN', '', '', '', ''],
    'Commercial Clients': ['PIC', 'Time Stamp', 'Closed Date', 'First Contact Date',
        'Closing Time', 'CUSTOMER ID', 'Ad', '', 'No Telefon', 'Alamat', 'EMEL',
        'PREMISE (RESIDENTIAL / COMMERCIAL)', 'Total Session', 'Done Session',
        'Balance Session', 'First Session Date', 'Second Session Date', 'Third Session Date',
        'PREVIOUS SESSION (Subscription)', 'Next Session Date (Subscription)',
        'TRBS (YES / NO)', 'TRBS COLLECTION DATE', 'CLEAR / DEPOSIT', 'TYPE OF PEST',
        'TYPE OF PACKAGE', 'Total (RM)', 'DEPOSIT PAID (RM)', 'INVOICE ID',
        'BALANCE PAID (RM)', ''],
    'REFUND': ['Date', 'Customer ID', 'Customer Name', 'Phone No.', 'Purchase Date',
        'Reason for Refund', 'Amount', 'Bank Account No.', 'Bank Name',
        'Complete / Pending', ''],
    'Recurring Payments': ['', '', 'Closed Date', '', 'Cust ID', 'Ad', 'Customer Name',
        'Phone Number', 'Email', 'PREMISE (RESIDENTIAL / COMMERCIAL)', 'Total Sessions',
        'Balance Sessions', '1ST Session Date', 'CLEAR/ DEPOSIT', 'Type of Pest', 'Package',
        'Contract Type', 'Total (MYR)', 'Deposit Paid ( MYR )', 'Payment Type',
        'Balance Paid ( MYR )', 'Balance Payment', '2nd Payment', '3rd Payment',
        '4th Payment', '5th Payment', '6th Payment', '7th Payment', '8th Payment',
        '9th Payment', '10th Payment', '11th Payment', '12th Payment'],
}
PREFIXES = {
    'B2B FOLLOW UP': 'b2b_follow_up', 'SALES': 'sales', 'PAYMENTS': 'payments',
    'PAYMENT LINK': 'payment_link', 'WARRANTY CLAIM': 'warranty_claim',
    'Commercial Clients': 'commercial_clients', 'REFUND': 'refund',
    'Recurring Payments': 'recurring_payments',
}
